- name: setup template
  ansible.builtin.template:
    src: pipeline.xml
    dest: /tmp/pipeline.xml

- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/pipeline.xml') }}"
    name: test
    password: Jenkins
    url: http://172.31.93.116:8080
    user: Jenkins